from enum import Enum

class ColumnName(Enum):
    id = 'id'
    drawing = 'drawing'
    sheet = 'sheet'
    line_number = 'line_number'
    pipe_spec = 'pipe_spec'
    paint_spec = 'paint_spec'
    insulation_spec = 'insulation_spec'
    pwht = 'pwht'
    p_and_id = 'p_and_id'
    area = 'area'
    item = 'item'
    tag = 'tag'
    quantity = 'quantity'
    nps = 'nps'
    material_description = 'material_description'
    heat_trace = 'heat_trace'
    insulation_type = 'insulation_type'
    insulation_thickness = 'insulation_thickness'
    process_line_list = 'process_line_list'
    documents = 'documents'